name: ganjine
description: Collection of high school social studies questions.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^0.1.3
  http: ^0.12.1
  lottie: ^0.3.6
  sweetsheet: ^0.2.0
  random_color: ^1.0.5
  auto_size_text: ^2.1.0
  font_awesome_flutter: ^8.8.1




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/backgrounds/
    - assets/images/
    - assets/lottie/


  fonts:
    - family: DimaKhabar2
      fonts:
        - asset:  assets/fonts/DimaKhabar2.ttf

    - family: DimaFred
      fonts:
        - asset:  assets/fonts/DimaFred.ttf